CREATE TABLE IF NOT EXISTS SPRINT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PROJECT_ID BIGINT NOT NULL 
);        
               
CREATE TABLE IF NOT EXISTS SPRINT_USER_STORY(
    SPRINT_ID BIGINT,
    USER_STORY_ID BIGINT
);